---

name: Draft Release

on:
  push:
    # Run on merge into a main branch, which covers merged pull requests
    branches:
      - main
      - master
  pull_request:
    # Run on new pull request so that autolabeling happens
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
