---

name: Release

on:
  pull_request:
    # Run on new/reopened pull requests so that autolabeling happens
    types: [opened, reopened, synchronize]
  push:
    # Run on change in the main branch, which covers merged pull requests
    branches:
      - main
      - master

jobs:
  update_release:
    name: "Update"
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
